substitutions:
  name: office-echo
  friendly_name: Office-Echo
  area: "Office"
  default_speaker: media_player.office
  mic_gain: "10"
  encrypt_key: "REPLACE_ME" # User must supply their own secrets.
  ota_pass: "REPLACE_ME" # User must supply their own secrets.
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_password

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:
  encryption:
    key: ${encrypt_key}
ota:
  - platform: esphome
    password: ${ota_pass}
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}

packages:
  default: !include atom_echo_firmware.yaml
